# Generated by Django 2.0.2 on 2018-04-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otklik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Ожидание'), ('A', 'Согласие'), ('D', 'Отклонено')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='otklik',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamapp.Vacancy'),
        ),
        migrations.AddField(
            model_name='otklik',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerProfile'),
        ),
    ]
